# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Define custom palette
palette = "catppuccin_mocha" 

# Use custom format
format = """ 
[](base)\
$os\
$username\
$python\
[](bg:lavender fg:base)\
$directory\
[](fg:lavender bg:blue)\
$git_branch\
$git_status\
[](fg:blue bg:sky)\
$nodejs\
[](fg:sky bg:base)\
$status\
[](fg:base)\
"""

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = false

[os]
format = "[$symbol ]($style)"
style = "bg:base fg:text"
disabled = false

[os.symbols]
Windows = ""
Arch = "󰣇"

[username]
show_always = true
format = "[$user ]($style)"
style_user = "bg:base fg:text"
style_root = "bg:base fg:text"
aliases = { "Administrator" = "s0mbra " }

[directory]
style = "bg:lavender fg:mantle"
format = "[ $path ]($style)"
truncation_length = 4
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:blue fg:mantle"
format = "[ $symbol $branch ]($style)"

[git_status]
style = "bg:blue fg:mantle"
format = "[$all_status$ahead_behind ]($style)"
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'

[status]
symbol = "\uf071"
success_symbol = ""
map_symbol = true
disabled = false
style = "bg:base fg:peach"
format = "[ $symbol ]($style)"

[python]
symbol = ""
style = "bg:base fg:peach"
version_format = "${major}.${minor}"
format = "[ $symbol$virtualenv $version ]($style)"

[nodejs]
symbol = ""
format = "[ $symbol $version ]($style)"
style = "bg:sky fg:mantle"

# Define custom colors
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
