"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
final_space = true
version = 2

[[blocks]]
type = "prompt"
alignment = "left"

  [[blocks.segments]]
    type = "os"
    style = "diamond"
    leading_diamond = ""
    foreground = "#CDD6F4"
    background = "#1E1E2E"
    template = "{{ if .WSL }}WSL at {{ end }}{{.Icon}} "

  [[blocks.segments]]
    type = "session"
    style = "diamond"
    foreground = "#cdd6f4"
    background = "#1e1e2e"
    template = "{{ .UserName }} "

  [[blocks.segments]]
    type = "root"
    style = "diamond"
    foreground = "#f9e2af"
    background = "#1e1e2e"
    template = "<parentBackground></> "

    [blocks.segments.properties]
      root_icon = "#"

  [[blocks.segments]]
  type = "path"
  style = "powerline"
  powerline_symbol = ""
  foreground = "#181825"
  background = "#b4befe"
  template = " {{ .Path }} "

    [blocks.segments.properties]
    style = "full"

  [[blocks.segments]]
  type = "git"
  style = "powerline"
  powerline_symbol = ""
  foreground = "#181825"
  background = "#89b4fa"
  background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}#ffeb95{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#c5e478{{ end }}', '{{ if gt .Ahead 0 }}#C792EA{{ end }}', '{{ if gt .Behind 0 }}#C792EA{{ end }}']
  template = ' {{ .HEAD }} {{ if .Working.Changed }}{{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}<#ef5350>  {{ .Staging.String }}</>{{ end }} '

    [blocks.segments.properties]
      branch_icon = ' '
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    type = "status"
    style = "diamond"
    foreground = "#fab387"
    background = "#1e1e2e"
    foreground_templates = [ "{{ if .Error }}#181825{{ end }}" ]
    background_templates = [ "{{ if .Error }}#f38ba8{{ end }}" ]
    trailing_diamond = ""
    template = " {{ if eq .Code 0 }}  {{ else }} \uf071 {{ end }}"

    [blocks.segments.properties]
      always_enabled = true
