"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
final_space = true
version = 2

[[blocks]]
type = "prompt"
alignment = "left"

  [[blocks.segments]]
    type = "os"
    style = "diamond"
    leading_diamond = ""
    foreground = "p:text"
    background = "p:base"
    template = "{{ if .WSL }}WSL at {{ end }}{{.Icon}} "

  [[blocks.segments]]
    type = "session"
    style = "diamond"
    foreground = "p:text"
    background = "p:base"
    template = "{{ .UserName }} "

  [[blocks.segments]]
    type = "root"
    style = "diamond"
    foreground = "p:yellow"
    background = "p:base"
    template = "<parentBackground></> "

    [blocks.segments.properties]
      root_icon = "#"

  [[blocks.segments]]
    type = "python"
    style = "diamond"
    foreground = "p:mantle"
    background = "p:blue"
    template = "<parentBackground></>  {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Major }}.{{ .Minor }}{{ end }} "

  [[blocks.segments]]
  type = "path"
  style = "powerline"
  powerline_symbol = ""
  foreground = "p:mantle"
  background = "p:lavender"
  template = " {{ .Path }} "

    [blocks.segments.properties]
    style = "folder"

      [blocks.segments.properties.mapped_locations]
      "C:\\Users\\s0mbra\\.config" = " config"

  [[blocks.segments]]
  type = "git"
  style = "powerline"
  powerline_symbol = ""
  foreground = "p:mantle"
  background = "p:blue"
  background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}#ffeb95{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#c5e478{{ end }}', '{{ if gt .Ahead 0 }}#C792EA{{ end }}', '{{ if gt .Behind 0 }}#C792EA{{ end }}']
  template = ' {{ .HEAD }} {{ if .Working.Changed }}{{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}<#ef5350>  {{ .Staging.String }}</>{{ end }} '

    [blocks.segments.properties]
      branch_icon = " "
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    type = "status"
    style = "diamond"
    foreground = "p:peach"
    background = "p:base"
    foreground_templates = [ "{{ if .Error }}p:mantle{{ end }}" ]
    background_templates = [ "{{ if .Error }}p:red{{ end }}" ]
    trailing_diamond = ""
    template = " {{ if eq .Code 0 }}  {{ else }} \uf071 {{ end }}"

    [blocks.segments.properties]
      always_enabled = true

[palette]
  lavender = "#B4BEFE"
  mantle = "#181825"
  text = "#CDD6F4"
  base = "#1E1E2E"
  yellow = "#F9E2AF"
  blue = "#89B4FA"
  peach = "#FAB387"
  red = "#F38BA8"
